name: dmm-check-pr
on:
  pull_request:
    branches:
      - master
      
jobs:
  build:
    name: Build dmm.exe
    runs-on: windows-2019
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: Declare some variables
        id: vars
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      
      - name: Build 7zip cmake files
        shell: cmd
        run: call Script\7zppMSVCBuild\PreBuild.bat
      
      - name: Build 7zip
        shell: cmd
        run: call Script\7zppMSVCBuild\BuildRelease.bat
        env:
          vsPlatform: Enterprise
          
      - name: Build wxWidgets
        shell: cmd
        run: call Script\wxWidgetsMSVCBuild\BuildRelease.bat
        env:
          vsPlatform: Enterprise
          
      - name: Build mod manager
        shell: cmd
        run: call VisualStudio\Build.bat
        env:
          vsPlatform: Enterprise
        
      - name: Artifact upload
        uses: actions/upload-artifact@v2
        with:
          name: DMM ${{ steps.vars.outputs.sha_short }}         
          path: VisualStudio\Release\dmm.exe