name: dmm-check-pr
on:
  pull_request:
    branches:
      - master
      
jobs:
  build:
    name: Build dmm.exe
    runs-on: windows-2019
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: Declare some variables
        id: vars
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          
      - name: Build mod manager
        shell: cmd
        run: |
          cmake -G "Visual Studio 16 2019" -B "Build" -A Win32
          cmake --build Build --config Release --target "dmm"
        env:
          vsPlatform: Enterprise
        
      - name: Artifact upload
        uses: actions/upload-artifact@v2
        with:
          name: DMM ${{ steps.vars.outputs.sha_short }}         
          path: Build\Release\dmm.exe